server:
  port: 8081

spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/devdojo?sslMode=DISABLED&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: devdojo