version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_microservices
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: devdojo
    volumes:
      - microservices_devdojo:/var/lib/mysql

volumes:
  microservices_devdojo:

#   RUN COMMAND:
#    docker-compose -f stack.yml up